version: '3.8'

services:
  # --- BACKEND ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: astra_backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
      - NODE_ENV=production
      # Permite que o frontend acesse o backend
      - ALLOWED_ORIGINS=https://gestao.btwdata.tech,http://localhost
    volumes:
      - contacts_data:/app/data
      - uploads_data:/app/uploads
      - backup_data:/app/backups
    networks:
      - traefik_public
      - internal_net
    labels:
      - "traefik.enable=true"
      # O Backend atende em /api
      - "traefik.http.routers.gestao-api.rule=Host(`gestao.btwdata.tech`) && PathPrefix(`/api`)"
      - "traefik.http.routers.gestao-api.entrypoints=websecure"
      - "traefik.http.routers.gestao-api.tls=true"
      - "traefik.http.routers.gestao-api.tls.certresolver=le"
      - "traefik.http.services.gestao-api.loadbalancer.server.port=3001"

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: astra_frontend
    restart: always
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      # O Frontend atende todo o resto
      - "traefik.http.routers.gestao-web.rule=Host(`gestao.btwdata.tech`)"
      - "traefik.http.routers.gestao-web.entrypoints=websecure"
      - "traefik.http.routers.gestao-web.tls=true"
      - "traefik.http.routers.gestao-web.tls.certresolver=le"
      - "traefik.http.services.gestao-web.loadbalancer.server.port=80"

  # --- BANCO DE DADOS (Opcional se já tiver externo) ---
  postgres:
    image: postgres:16-alpine
    container_name: astra_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  redis:
    image: redis:7-alpine
    container_name: astra_redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - internal_net

volumes:
  postgres_data:
  redis_data:
  contacts_data:
  uploads_data:
  backup_data:

networks:
  traefik_public:
    external: true
  internal_net:
    driver: bridge